---
title: "Benchmark_cross_validation_parallel_and_sequential"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmark_cross_validation_parallel_and_sequential}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=4, 
  fig.height=2,
  fig.align = "center"
)
```

```{r setup, warning=FALSE}
library(cpp)
library(bench)
library(ggplot2)
library(dplyr)
library(parallel)

#The aim is to compare, in terms of time of computation, the sequential and the parallel version of the 
#function for k-fold cross validation

#we construct a function to show the result of the benchmark in a plot 
print_bench <- function(bm) {
  bm %>% 
    mutate(expression = as.character(expression))
}

show_bm <- function(bm) {
  print(print_bench(bm))
  #autoplot(bm)
}

#we show the benchmark plot
bench::mark(
  sequential={round(cpp::cvsequencial(100,Dep.var~.,mydataset,1e-5,1000,1e-5,F),4)},
  parallel={round(cpp::cvparallel(100,Dep.var~.,mydataset,1e-5,1000,1e-5,F,detectCores()-1 ),4)}) %>% show_bm()
#we see that the parallel version is more efficient
```
