---
title: "parallel_cross_validation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{parallel_cross_validation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cpp)
library(dplyr)
library(parallel)

#we want to see how the sequential cross validation works on the Gradient Descent Optimization Method for Linear Models 
#varying the number of groups created (in the case of 1000 folds and 100 folds)
cpp::cvparallel(1000,Dep.var~.,mydataset,1e-5,1000,1e-5,F, FdetectCores()-1)
cpp::cvparallel(100,Dep.var~.,mydataset,1e-5,1000,1e-5,F, FdetectCores()-1)

#we want to see how the sequential cross validation works on the Gradient Descent Optimization Method for Linear Models 
#varying the stopping criteria (in the case of tolerance level of 1e-3 and 1e-6)
cpp::cvparallel(100,Dep.var~.,mydataset,1e-3,1000,1e-3,F, FdetectCores()-1)
cpp::cvparallel(100,Dep.var~.,mydataset,1e-6,1000,1e-6,FdetectCores()-1)
```
