// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// betahat_GD_Cpp
arma::vec betahat_GD_Cpp(arma::vec beta, arma::mat X, arma::vec Y, double tolerance, int maxit, double stepsize);
RcppExport SEXP _cpp_betahat_GD_Cpp(SEXP betaSEXP, SEXP XSEXP, SEXP YSEXP, SEXP toleranceSEXP, SEXP maxitSEXP, SEXP stepsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type stepsize(stepsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(betahat_GD_Cpp(beta, X, Y, tolerance, maxit, stepsize));
    return rcpp_result_gen;
END_RCPP
}
// betahat_SD_Cpp
arma::vec betahat_SD_Cpp(arma::vec beta, arma::mat X, arma::vec Y, double tolerance);
RcppExport SEXP _cpp_betahat_SD_Cpp(SEXP betaSEXP, SEXP XSEXP, SEXP YSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(betahat_SD_Cpp(beta, X, Y, tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cpp_betahat_GD_Cpp", (DL_FUNC) &_cpp_betahat_GD_Cpp, 6},
    {"_cpp_betahat_SD_Cpp", (DL_FUNC) &_cpp_betahat_SD_Cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_cpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
