# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimation Linear Regression model via Gradient Descend method
#' @title betahat_GD_Cpp
#' @name betahat_GD_Cpp
#' @param beta initial guess beta vector
#' @param X design matrix
#' @param Y response variable vector
#' @param tolerance level
#' @param maxit max num of iter
#' @param stepsize learning parameter
#' @export
NULL

betahat_GD_Cpp <- function(beta, X, Y, tolerance, maxit, stepsize) {
    .Call(`_cpp_betahat_GD_Cpp`, beta, X, Y, tolerance, maxit, stepsize)
}

#' Estimation Linear Regression model via Steepest Descend method
#' @title betahat_SD_Cpp
#' @name betahat_SD_Cpp
#' @param beta initial guess beta vector
#' @param X design matrix
#' @param Y response variable vector
#' @param tolerance level
#' @export
#' 
betahat_SD_Cpp <- function(beta, X, Y, tolerance, maxit) {
    .Call(`_cpp_betahat_SD_Cpp`, beta, X, Y, tolerance, maxit)
}

